### ISSUE TITLE
bug: Firebase functions의 로그에서 resetDailyCountsAndPoints 함수의 오류 확인

### ISSUE THREAD

**Issue by pkh31337** [pkh31337/SpeakEasy_firebase_functions#1]
Firebase functions의 로그에서 오류 확인

###오류###

ERROR 2024-05-22T15:00:07.551213Z [resource.labels.functionName: resetDailyCountsAndPoints] [labels.executionId: aadbq5nnx0mh] TypeError: Cannot read properties of undefined (reading 'map') at /workspace/lib/index.js:123:80 at Array.map (<anonymous>) at /workspace/lib/index.js:101:35 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
{
"textPayload": "TypeError: Cannot read properties of undefined (reading 'map')\n    at /workspace/lib/index.js:123:80\n    at Array.map (<anonymous>)\n    at /workspace/lib/index.js:101:35\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)",
"insertId": "664e08770008692d4fc498b9",
"resource": {
"type": "cloud_function",
"labels": {
"project_id": "speakeasy-6e7c8",
"region": "asia-northeast3",
"function_name": "resetDailyCountsAndPoints"
}
},
"timestamp": "2024-05-22T15:00:07.551213Z",
"severity": "ERROR",
"labels": {
"instance_id": "00f46b92852d20ebad033bbc597b9b5f856fecdf5985e1247a3725e4eb47ee382ddb024419f35de0e71d6bc1ce231e119a363fde3084b1c093698b115326e02e29b6",
"execution_id": "aadbq5nnx0mh",
"runtime_version": "nodejs18_20240513_18_20_2_RC00"
},
"logName": "projects/speakeasy-6e7c8/logs/cloudfunctions.googleapis.com%2Fcloud-functions",
"trace": "projects/speakeasy-6e7c8/traces/cfe093cfaaaf10766ff02db97069ee99",
"receiveTimestamp": "2024-05-22T15:00:07.684826088Z",
"errorGroups": [
{
"id": "CN6OrrHfw92qKQ"
}
]
}

**Comment by pkh31337** [comment]
해당 오류 메시지를 분석해보면, TypeError: Cannot read properties of undefined (reading 'map') 오류가 발생했습니다. 이 오류는 map 함수를 호출하려고 했지만, 호출 대상이 undefined인 상황에서 발생합니다. 여기서 문제가 되는 부분은 currentPartnerFavorPoints 필드를 map 함수로 처리하려고 했을 때 currentPartnerFavorPoints 자체가 undefined일 가능성이 높습니다.

이를 해결하기 위해서는 currentPartnerFavorPoints 필드가 undefined인 경우를 대비한 처리가 필요합니다. 아래 코드에서는 currentPartnerFavorPoints 필드가 undefined이거나 비어있는 배열인 경우 빈 배열을 사용하게 수정했습니다:

javascript


exports.resetDailyCountsAndPoints = functions.region("asia-northeast3").pubsub.schedule("0 0 * * *")
  .timeZone("Asia/Seoul") // 시간대 설정. 필요에 따라 변경하세요.
  .onRun(async (context) => {
    const usersRef = admin.firestore().collection("users");
    const snapshot = await usersRef.get();

    const updates = snapshot.docs.map(async (doc) => {
      // isAnonymous가 true인 경우 업데이트를 진행하지 않음
      if (doc.data().isAnonymous) {
        return Promise.resolve();
      }

      // daily * AchievementCount 필드들을 0으로 초기화
      const resetAchievements = {
        dailyMessageAchievementCount: 0,
        dailyReplyAchievementCount: 0,
        dailyPostAchievementCount: 0,
        dailyCommentAchievementCount: 0,
        dailyLoginAchievementCount: 0,
        dailyChatAchievementCount: 0,
        dailyReviewAchievementCount: 0,
        dailyPartnerAchievementCount: 0,
        dailyFlashcardAchievementCount: 0,
        dailyEventAchievementCount: 0,
      };

      // currentGeneralPoint 필드에서 10을 빼고, 결과가 0보다 작으면 0으로 조정
      const newGeneralPoint = doc.data().currentGeneralPoint ? doc.data().currentGeneralPoint - 10 : -10;
      const adjustedGeneralPoint = Math.max(0, newGeneralPoint);

      // currentPartnerFavorPoints 배열의 각 요소에서 10을 빼고, 결과가 0보다 작으면 0으로 조정
      // currentPartnerFavorPoints가 undefined일 경우 빈 배열([])을 사용
      const adjustedPartnerFavorPoints = (doc.data().currentPartnerFavorPoints || []).map(point => Math.max(0, point - 10));

      // 문서 업데이트
      return doc.ref.update({
        ...resetAchievements,
        currentGeneralPoint: adjustedGeneralPoint,
        currentPartnerFavorPoints: adjustedPartnerFavorPoints,
      });
    });

    // 모든 업데이트를 기다림
    await Promise.all(updates);
    console.log("Daily counts and points have been reset and adjusted for non-anonymous users.");
  });
위 코드에서는 doc.data().currentPartnerFavorPoints || []를 사용하여 currentPartnerFavorPoints 필드가 undefined인 경우 대신 빈 배열을 사용하도록 했습니다. 이렇게 하면 map 함수 호출 시 undefined 때문에 발생하는 오류를 방지할 수 있습니다.
